name: publish packages

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install front-end dependencies
        working-directory: ui/
        run: npm ci --force

      - name: Build front-end
        working-directory: ui/
        run: npm run build
        
      - name: Set up Go
        uses: actions/setup-go@v4
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
